local vim = vim
local telescope_builtin = require("telescope.builtin")

vim.keymap.set("n", "-", vim.cmd.Oil)
vim.keymap.set("n", "<Space>u", vim.cmd.UndotreeToggle)
vim.keymap.set({ "n", "v" }, "<Space>cc", vim.cmd.CopilotChatToggle)
vim.keymap.set({ "n", "v" }, "<Space>cr", vim.cmd.CopilotChatReview)
vim.keymap.set({ "n", "v" }, "<Space>cf", vim.cmd.CopilotChatFix)
vim.keymap.set({ "n", "v" }, "<Space>co", vim.cmd.CopilotChatOptimize)
vim.keymap.set("n", "<Space><Space>", telescope_builtin.buffers)
vim.keymap.set("n", "<Space>fd", telescope_builtin.fd)
vim.keymap.set("n", "<Space>ff", telescope_builtin.live_grep)
vim.keymap.set("n", "<Space>re", telescope_builtin.registers)
vim.keymap.set("n", "<Space>dd", telescope_builtin.diagnostics)
vim.keymap.set("n", "<Space>do", "<cmd>lua vim.diagnostic.open_float()<cr>")
vim.keymap.set("n", "<Space>dn", "<cmd>lua vim.diagnostic.goto_next()<cr>")
vim.keymap.set("n", "<Space>dp", "<cmd>lua vim.diagnostic.goto_prev()<cr>")
