#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
# picom &
xset s off &
xset -dpms &
xset -b &
feh --bg-scale ~/Pictures/Wallpapers/platform.jpg &
~/.config/polybar/scripts/launch.sh
xrandr --output DP-2 --mode 1920x1080 --rate 120 &
xinput set-prop 15 312 1 &
xinput set-prop 15 291 1 &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width 2
bspc config window_gap  10
bspc config split_ratio 0.60
bspc config borderless_monocle true
bspc config gapless_monocle true
