#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
picom &
feh --bg-scale ~/Pictures/gruvbox.png
xrandr --rate 120 &
~/.config/polybar/launch.sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12
bspc config split_ratio          0.60
bspc config borderless_monocle   true
bspc config gapless_monocle      true

