require("arunav.configs.lsp")
require("arunav.configs.theme")
require("arunav.configs.telescope")
require("arunav.configs.which_key")
require("arunav.configs.treesitter")
require("arunav.configs.autopairs")
require("arunav.configs.lualine")
-- require("arunav.configs.nvimtree")
require("arunav.configs.gitsigns")
