icons_format = "{icon}"

[theme]
theme = "plain"

[icons]
icons = "material-nf"


[[block]]
block = "cpu"
format = " $icon $utilization "
format_alt = " $icon $frequency "
info_cpu = 20
warning_cpu = 50
critical_cpu = 90

[[block]]
block = "amd_gpu"

[[block]]
block = "memory"
format = " $icon $mem_used_percents "
format_alt = " $icon_swap $swap_used_percents "
warning_mem = 50
critical_mem = 75
warning_swap = 10
critical_swap = 50

[[block]]
block = "temperature"
format = " $icon $max max "
format_alt = " $icon $min min, $max max, $average avg "
interval = 10

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
warning = 20.0
alert = 10.0
format = " $icon $available "
format_alt = " $icon $percentage "

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "backlight"
device = "amdgpu_bl1"

[[block]]
block = "hueshift"
format = " $temperature K "

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d/%m %R') "

[[block]]
block = "battery"
format = " $power $icon $percentage $time "

[[block]]
block = "notify"

[[block]]
block = "menu"
text = " \uf011 "
[[block.items]]
display = " > Suspend "
cmd = "systemctl suspend"
[[block.items]]
display = " > Shutdown "
cmd = "poweroff"
confirm_msg = "Are you sure you want to power off?"
[[block.items]]
display = " > Reboot "
cmd = "reboot"
confirm_msg = "Are you sure you want to reboot?"
