source = ~/.config/hypr/conf.d/general.conf
source = ~/.config/hypr/conf.d/decoration.conf
source = ~/.config/hypr/conf.d/animations.conf
source = ~/.config/hypr/conf.d/input.conf
source = ~/.config/hypr/conf.d/gestures.conf
source = ~/.config/hypr/conf.d/misc.conf
source = ~/.config/hypr/conf.d/binds.conf
source = ~/.config/hypr/conf.d/monitors.conf
source = ~/.config/hypr/conf.d/autostart.conf

