exec = pkill waybar; waybar &
exec = nm-applet &
exec = blueman-applet &

exec-once = wl-paste --type text --watch cliphist store &
exec-once = wl-paste --type image --watch cliphist store &
exec-once = hyprpaper &
exec-once = swaync &
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

