$left = h
$down = j
$up = k
$right = l

bind = SUPER, RETURN, exec, ghostty
bind = SUPER, W, togglegroup,
bind = SUPER-SHIFT, R, exec, hyprctl reload
bind = SUPER-SHIFT, Q, killactive,
bind = SUPER-SHIFT, SPACE, togglefloating,
bind = SUPER-SHIFT, F, fullscreen,
bind = SUPER, Space, exec, wmenu-run -b -f "JetBrainsMono Nerd Font Mono 12"
bind = SUPER, P, exec, grim ~/Pictures/Screenshots/$(date +%F_%T).png
bind = SUPER-SHIFT, P, exec, grim -g "$(slurp)" ~/Pictures/Screenshots/$(date +%F_%T).png

bind = SUPER, $left, movefocus, l
bind = SUPER, $right, movefocus, r
bind = SUPER, $up, movefocus, u
bind = SUPER, $down, movefocus, d

bind = SUPER-SHIFT, $left, movewindow, l
bind = SUPER-SHIFT, $right, movewindow, r
bind = SUPER-SHIFT, $up, movewindow, u
bind = SUPER-SHIFT, $down, movewindow, d

bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2
bind = SUPER, 3, workspace, 3
bind = SUPER, 4, workspace, 4
bind = SUPER, 5, workspace, 5
bind = SUPER, 6, workspace, 6
bind = SUPER, 7, workspace, 7
bind = SUPER, 8, workspace, 8
bind = SUPER, 9, workspace, 9
bind = SUPER, 0, workspace, 10

bind = SUPER-SHIFT, 1, movetoworkspacesilent, 1
bind = SUPER-SHIFT, 2, movetoworkspacesilent, 2
bind = SUPER-SHIFT, 3, movetoworkspacesilent, 3
bind = SUPER-SHIFT, 4, movetoworkspacesilent, 4
bind = SUPER-SHIFT, 5, movetoworkspacesilent, 5
bind = SUPER-SHIFT, 6, movetoworkspacesilent, 6
bind = SUPER-SHIFT, 7, movetoworkspacesilent, 7
bind = SUPER-SHIFT, 8, movetoworkspacesilent, 8
bind = SUPER-SHIFT, 9, movetoworkspacesilent, 9
bind = SUPER-SHIFT, 0, movetoworkspacesilent, 10

# Example special workspace (scratchpad)
bind = SUPER, MINUS, togglespecialworkspace, magic
bind = SUPER-SHIFT, MINUS, movetoworkspace, special:magic

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = SUPER, mouse:272, movewindow
bindm = SUPER, mouse:273, resizewindow

bind = SUPER, R, submap, resize
submap = resize
binde = , $right, resizeactive, 20 0
binde = , $left, resizeactive, -20 0
binde = , $up, resizeactive, 0 -20
binde = , $down, resizeactive, 0 20

bind = , escape, submap, reset
submap = reset

# Laptop multimedia keys for volume and LCD brightness
bindel = ,XF86AudioRaiseVolume, exec, pactl set-sink-volume @DEFAULT_SINK@ +5%
bindel = ,XF86AudioLowerVolume, exec, pactl set-sink-volume @DEFAULT_SINK@ -5%
bindel = ,XF86AudioMute, exec, pactl set-sink-mute @DEFAULT_SINK@ toggle
bindel = ,XF86AudioMicMute, exec, pactl set-source-mute @DEFAULT_SOURCE@ toggle
bindel = ,XF86MonBrightnessUp, exec, light -A 10
bindel = ,XF86MonBrightnessDown, exec, light -U 10
bindel = ,XF86AudioPlay, exec, playerctl play-pause
bindel = ,XF86AudioNext, exec, playerctl next
bindel = ,XF86AudioPrev, exec, playerctl previous
