general {
    border_size = 2
    gaps_in = 4
    gaps_out = 8
    gaps_workspaces = 32
    # col.active_border = rgb(fab387) rgb(b4befe) rgb(a6e3a1) 45deg
    # col.inactive_border = rgb(585b70) rgb(313244) rgb(585b70) 45deg
    layout = master
}
